sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java
sonar.cpd.exclusions=src/main/java/pitchmarketplace/domain/entity/Pitch.java,src/main/java/pitchmarketplace/dto/PitchSearchRequest.java
