sonar.exclusions=lab_1/**,**/lab_1/**
sonar.cpd.exclusions=lab_1/**,**/lab_1/**,src/main/java/by/bsuir/pitchmarketplace/domain/entity/Pitch.java,src/main/java/by/bsuir/pitchmarketplace/dto/PitchSearchRequest.java
