sonar.sources=lab_1/src/main/java,lab_1/src/main/resources
sonar.tests=lab_1/src/test/java
sonar.cpd.exclusions=lab_1/src/main/java/by/bsuir/pitchmarketplace/domain/entity/Pitch.java,lab_1/src/main/java/by/bsuir/pitchmarketplace/dto/PitchSearchRequest.java
