sonar.organization=saku102007
sonar.projectKey=SAKU102007_sem_4_java
sonar.projectName=sem_4_java
sonar.host.url=https://sonarcloud.io
sonar.sources=lab_1/src/main/java,lab_1/src/main/resources
sonar.tests=lab_1/src/test/java
sonar.java.binaries=lab_1/target/classes
sonar.sourceEncoding=UTF-8
