sonar.organization=saku102007
sonar.projectKey=SAKU102007_sem_4_java
sonar.projectName=sem_4_java
sonar.host.url=https://sonarcloud.io
sonar.sources=src/main/java,src/main/resources
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.sourceEncoding=UTF-8
